//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Data.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int StatisticID { get; set; }
        public int UserID { get; set; }
        public int TestID { get; set; }
        public int CorrectAnswer { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
